<a href="https://colab.research.google.com/github/RakshanURK20CS1154/Dataset/blob/main/URK20CS1154_ML_LAB_EXP1b_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Stores (2).csv')
df

,Branch,City,Customer,Gender,Product line,Unit_price,Quantity,Tax,Total,Payment,cogs,Rating,Age,Quarterly_Tax,Price
0,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,Ewallet,522.83,9.1,23,210,7469
1,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,Cash,76.40,9.6,23,210,1528
2,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,Credit card,324.31,7.4,24,210,4633
3,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,Ewallet,465.76,8.4,26,210,5822
4,A,Yangon,Normal,Male,Sports and travel,86.31,60,30.2085,634.3785,Ewallet,604.17,5.3,30,210,8631
5,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,Ewallet,597.73,4.1,32,210,8539
6,A,Yangon,Member,Female,NaN,68.84,6,20.6520,433.6920,Ewallet,413.04,5.8,27,210,6884
7,C,Naypyitaw,Normal,Female,NaN,73.56,10,36.7800,772.3800,Ewallet,735.60,8.0,30,210,7356
8,A,Yangon,Member,Female,NaN,36.26,2,3.6260,76.1460,Credit card,72.52,7.2,27,100,3626
9,B,Mandalay,Member,Female,NaN,54.84,3,8.2260,172.7460,Credit card,164.52,5.9,23,185,5484
10,B,Mandalay,Member,Female,NaN,14.48,4,2.8960,60.8160,Ewallet,57.92,4.5,25,100,1448
11,B,Mandalay,Member,Male,NaN,25.51,4,5.1020,107.1420,Cash,102.04,6.8,22,100,2551
12,A,Yangon,Normal,Female,Electronic accessories,46.95,5,11.7375,246.4875,Ewallet,234.75,7.1,25,100,4695
13,A,Yangon,Normal,Male,Food and beverages,43.19,10,21.5950,453.4950,Ewallet,431.90,8.2,31,100,4319
14,A,Yangon,Normal,Female,Health and beauty,71.38,10,35.6900,749.4900,Cash,713.80,5.7,32,100,7138
15,B,Mandalay,Member,Female,Sports and travel,93.72,6,28.1160,590.4360,Cash,562.32,4.5,28,100,9372
16,A,Yangon,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,Credit card,482.51,4.6,30,100,6893
17,NaN,Yangon,Normal,Male,Sports and travel,72.61,6,21.7830,457.4430,Credit card,435.66,6.9,24,85,7261
18,NaN,Yangon,Normal,Male,Food and beverages,54.67,3,8.2005,172.2105,Credit card,164.01,8.6,24,19,5467
19,NaN,Mandalay,Normal,Female,Home and lifestyle,40.30,2,4.0300,84.6300,Ewallet,80.60,4.4,30,85,4030
20,NaN,Naypyitaw,Member,Male,Electronic accessories,86.04,5,21.5100,451.7100,Ewallet,430.20,4.8,30,85,8604
21,NaN,Mandalay,Normal,Male,Health and beauty,87.98,55,13.1970,277.1370,Ewallet,263.94,5.1,29,100,8798
22,B,Mandalay,Normal,Male,Home and lifestyle,33.20,2,3.3200,69.7200,Credit card,66.40,4.4,28,85,3320
23,A,Yangon,Normal,Male,Electronic accessories,34.56,5,8.6400,181.4400,Ewallet,172.80,9.9,28,85,3456
24,A,Yangon,Member,Male,Sports and travel,88.63,3,13.2945,279.1845,Ewallet,265.89,6.0,29,85,8863
25,A,Yangon,Member,Female,Home and lifestyle,52.59,8,21.0360,441.7560,Credit card,420.72,8.5,25,85,5259
26,B,Mandalay,Normal,Male,Fashion accessories,33.52,1,1.6760,35.1960,Cash,33.52,6.7,27,85,3352
27,A,Yangon,Normal,Female,Fashion accessories,87.67,2,8.7670,184.1070,Credit card,175.34,7.7,29,85,8767
28,B,Mandalay,Normal,Female,Food and beverages,88.36,5,22.0900,463.8900,Cash,441.80,9.6,28,85,8836
29,A,Yangon,Normal,Male,Health and beauty,24.89,9,11.2005,235.2105,Cash,224.01,7.4,30,85,2489
30,B,Mandalay,Normal,Male,Fashion accessories,94.13,5,23.5325,494.1825,Credit card,470.65,4.8,29,19,9413
31,B,Mandalay,Member,Male,Sports and travel,78.07,9,35.1315,737.7615,Cash,702.63,4.5,22,85,7807
32,B,Mandalay,Normal,Male,Sports and travel,83.78,8,33.5120,703.7520,Cash,670.24,5.1,27,85,8378
33,A,Yangon,Normal,Male,NaN,96.58,2,9.6580,202.8180,Credit card,193.16,5.1,26,85,9658
34,C,Naypyitaw,Member,Female,NaN,99.42,4,19.8840,417.5640,Ewallet,397.68,7.5,22,85,9942
35,C,Naypyitaw,Member,Female,NaN,68.12,1,3.4060,71.5260,Ewallet,68.12,6.8,26,85,6812
36,NaN,Yangon,Member,Male,NaN,62.62,5,15.6550,328.7550,Ewallet,313.10,7.0,25,85,6262
37,NaN,Yangon,Normal,Female,NaN,60.88,57,27.3960,575.3160,Ewallet,547.92,4.7,23,85,6088
38,NaN,Naypyitaw,Normal,Female,NaN,54.92,8,21.9680,461.3280,Ewallet,439.36,7.6,32,85,5492
39,NaN,Mandalay,Member,Male,NaN,30.12,8,12.0480,253.0080,Cash,240.96,7.7,27,85,3012
40,NaN,Mandalay,Member,Female,NaN,86.72,1,4.3360,91.0560,Ewallet,86.72,7.9,22,85,8672
41,NaN,Naypyitaw,Member,Male,NaN,56.11,2,5.6110,117.8310,Cash,112.22,6.3,27,85,5611
42,NaN,Mandalay,Member,Female,NaN,69.12,6,20.7360,435.4560,Cash,414.72,5.6,22,85,6912
43,C,Naypyitaw,Member,Female,NaN,98.70,8,39.4800,829.0800,Cash,789.60,7.6,27,234,9870
44,C,Naypyitaw,Member,Male,NaN,15.37,2,1.5370,32.2770,Cash,30.74,7.2,22,234,1537
45,B,Mandalay,Member,Female,Electronic accessories,93.96,4,18.7920,394.6320,Cash,375.84,9.5,23,234,9396
46,B,Mandalay,Member,Male,Health and beauty,56.69,9,25.5105,535.7205,Credit card,510.21,8.4,27,234,5669
47,B,Mandalay,Member,Female,Food and beverages,20.01,56,9.0045,189.0945,Ewallet,180.09,4.1,22,85,2001
48,B,Mandalay,Member,Male,Electronic accessories,18.93,6,5.6790,119.2590,Credit card,113.58,8.1,22,234,1893
49,B,Mandalay,Member,Male,Electronic accessories,18.93,6,5.6790,119.2590,Credit card,113.58,8.1,22,234,1893

In [ ]:
null = (df.isnull().sum() / len(df)) * 100
null[null > 0]

Branch          24.0
Product line    36.0
dtype: float64

In [ ]:
for i in range(0, len(null)): 
	if null[i] > 0 and null[i] < 10: 
		col_name = df.columns[i] 
		df[col_name].fillna(df[col_name].mean(), inplace=True) 

# Print dataframe 
print(df.to_string())

   Branch       City Customer  Gender            Product line  Unit_price  Quantity      Tax     Total      Payment    cogs  Rating  Age  Quarterly_Tax  Price
0       A     Yangon   Member  Female       Health and beauty       74.69         7  26.1415  548.9715      Ewallet  522.83     9.1   23            210   7469
1       C  Naypyitaw   Normal  Female  Electronic accessories       15.28         5   3.8200   80.2200         Cash   76.40     9.6   23            210   1528
2       A     Yangon   Normal    Male      Home and lifestyle       46.33         7  16.2155  340.5255  Credit card  324.31     7.4   24            210   4633
3       A     Yangon   Member    Male       Health and beauty       58.22         8  23.2880  489.0480      Ewallet  465.76     8.4   26            210   5822
4       A     Yangon   Normal    Male       Sports and travel       86.31        60  30.2085  634.3785      Ewallet  604.17     5.3   30            210   8631
5       C  Naypyitaw   Normal    Male  Electronic accessories       85.39         7  29.8865  627.6165      Ewallet  597.73     4.1   32            210   8539
6       A     Yangon   Member  Female                     NaN       68.84         6  20.6520  433.6920      Ewallet  413.04     5.8   27            210   6884
7       C  Naypyitaw   Normal  Female                     NaN       73.56        10  36.7800  772.3800      Ewallet  735.60     8.0   30            210   7356
8       A     Yangon   Member  Female                     NaN       36.26         2   3.6260   76.1460  Credit card   72.52     7.2   27            100   3626
9       B   Mandalay   Member  Female                     NaN       54.84         3   8.2260  172.7460  Credit card  164.52     5.9   23            185   5484
10      B   Mandalay   Member  Female                     NaN       14.48         4   2.8960   60.8160      Ewallet   57.92     4.5   25            100   1448
11      B   Mandalay   Member    Male                     NaN       25.51         4   5.1020  107.1420         Cash  102.04     6.8   22            100   2551
12      A     Yangon   Normal  Female  Electronic accessories       46.95         5  11.7375  246.4875      Ewallet  234.75     7.1   25            100   4695
13      A     Yangon   Normal    Male      Food and beverages       43.19        10  21.5950  453.4950      Ewallet  431.90     8.2   31            100   4319
14      A     Yangon   Normal  Female       Health and beauty       71.38        10  35.6900  749.4900         Cash  713.80     5.7   32            100   7138
15      B   Mandalay   Member  Female       Sports and travel       93.72         6  28.1160  590.4360         Cash  562.32     4.5   28            100   9372
16      A     Yangon   Member  Female       Health and beauty       68.93         7  24.1255  506.6355  Credit card  482.51     4.6   30            100   6893
17    NaN     Yangon   Normal    Male       Sports and travel       72.61         6  21.7830  457.4430  Credit card  435.66     6.9   24             85   7261
18    NaN     Yangon   Normal    Male      Food and beverages       54.67         3   8.2005  172.2105  Credit card  164.01     8.6   24             19   5467
19    NaN   Mandalay   Normal  Female      Home and lifestyle       40.30         2   4.0300   84.6300      Ewallet   80.60     4.4   30             85   4030
20    NaN  Naypyitaw   Member    Male  Electronic accessories       86.04         5  21.5100  451.7100      Ewallet  430.20     4.8   30             85   8604
21    NaN   Mandalay   Normal    Male       Health and beauty       87.98        55  13.1970  277.1370      Ewallet  263.94     5.1   29            100   8798
22      B   Mandalay   Normal    Male      Home and lifestyle       33.20         2   3.3200   69.7200  Credit card   66.40     4.4   28             85   3320
23      A     Yangon   Normal    Male  Electronic accessories       34.56         5   8.6400  181.4400      Ewallet  172.80     9.9   28             85   3456
24      A     Yangon   Member    Male       Sports and travel       88.63         3  13.2945  279.1845      Ewallet  265.89     6.0   29             85   8863
25      A     Yangon   Member  Female      Home and lifestyle       52.59         8  21.0360  441.7560  Credit card  420.72     8.5   25             85   5259
26      B   Mandalay   Normal    Male     Fashion accessories       33.52         1   1.6760   35.1960         Cash   33.52     6.7   27             85   3352
27      A     Yangon   Normal  Female     Fashion accessories       87.67         2   8.7670  184.1070  Credit card  175.34     7.7   29             85   8767
28      B   Mandalay   Normal  Female      Food and beverages       88.36         5  22.0900  463.8900         Cash  441.80     9.6   28             85   8836
29      A     Yangon   Normal    Male       Health and beauty       24.89         9  11.2005  235.2105         Cash  224.01     7.4   30             85   2489
30      B   Mandalay   Normal    Male     Fashion accessories       94.13         5  23.5325  494.1825  Credit card  470.65     4.8   29             19   9413
31      B   Mandalay   Member    Male       Sports and travel       78.07         9  35.1315  737.7615         Cash  702.63     4.5   22             85   7807
32      B   Mandalay   Normal    Male       Sports and travel       83.78         8  33.5120  703.7520         Cash  670.24     5.1   27             85   8378
33      A     Yangon   Normal    Male                     NaN       96.58         2   9.6580  202.8180  Credit card  193.16     5.1   26             85   9658
34      C  Naypyitaw   Member  Female                     NaN       99.42         4  19.8840  417.5640      Ewallet  397.68     7.5   22             85   9942
35      C  Naypyitaw   Member  Female                     NaN       68.12         1   3.4060   71.5260      Ewallet   68.12     6.8   26             85   6812
36    NaN     Yangon   Member    Male                     NaN       62.62         5  15.6550  328.7550      Ewallet  313.10     7.0   25             85   6262
37    NaN     Yangon   Normal  Female                     NaN       60.88        57  27.3960  575.3160      Ewallet  547.92     4.7   23             85   6088
38    NaN  Naypyitaw   Normal  Female                     NaN       54.92         8  21.9680  461.3280      Ewallet  439.36     7.6   32             85   5492
39    NaN   Mandalay   Member    Male                     NaN       30.12         8  12.0480  253.0080         Cash  240.96     7.7   27             85   3012
40    NaN   Mandalay   Member  Female                     NaN       86.72         1   4.3360   91.0560      Ewallet   86.72     7.9   22             85   8672
41    NaN  Naypyitaw   Member    Male                     NaN       56.11         2   5.6110  117.8310         Cash  112.22     6.3   27             85   5611
42    NaN   Mandalay   Member  Female                     NaN       69.12         6  20.7360  435.4560         Cash  414.72     5.6   22             85   6912
43      C  Naypyitaw   Member  Female                     NaN       98.70         8  39.4800  829.0800         Cash  789.60     7.6   27            234   9870
44      C  Naypyitaw   Member    Male                     NaN       15.37         2   1.5370   32.2770         Cash   30.74     7.2   22            234   1537
45      B   Mandalay   Member  Female  Electronic accessories       93.96         4  18.7920  394.6320         Cash  375.84     9.5   23            234   9396
46      B   Mandalay   Member    Male       Health and beauty       56.69         9  25.5105  535.7205  Credit card  510.21     8.4   27            234   5669
47      B   Mandalay   Member  Female      Food and beverages       20.01        56   9.0045  189.0945      Ewallet  180.09     4.1   22             85   2001
48      B   Mandalay   Member    Male  Electronic accessories       18.93         6   5.6790  119.2590  Credit card  113.58     8.1   22            234   1893
49      B   Mandalay   Member    Male  Electronic accessories       18.93         6   5.6790  119.2590  Credit card  113.58     8.1   22            234   1893

In [ ]:
for i in range(0, len(null)): 
	if null[i] > 0: 
		col_name = df.columns[i] 
		df[col_name].fillna(df[col_name].mode(), inplace=True) 

# Print dataframe 
print(df.to_string())

   Branch       City Customer  Gender            Product line  Unit_price  Quantity      Tax     Total      Payment    cogs  Rating  Age  Quarterly_Tax  Price
0       A     Yangon   Member  Female       Health and beauty       74.69         7  26.1415  548.9715      Ewallet  522.83     9.1   23            210   7469
1       C  Naypyitaw   Normal  Female  Electronic accessories       15.28         5   3.8200   80.2200         Cash   76.40     9.6   23            210   1528
2       A     Yangon   Normal    Male      Home and lifestyle       46.33         7  16.2155  340.5255  Credit card  324.31     7.4   24            210   4633
3       A     Yangon   Member    Male       Health and beauty       58.22         8  23.2880  489.0480      Ewallet  465.76     8.4   26            210   5822
4       A     Yangon   Normal    Male       Sports and travel       86.31        60  30.2085  634.3785      Ewallet  604.17     5.3   30            210   8631
5       C  Naypyitaw   Normal    Male  Electronic accessories       85.39         7  29.8865  627.6165      Ewallet  597.73     4.1   32            210   8539
6       A     Yangon   Member  Female                     NaN       68.84         6  20.6520  433.6920      Ewallet  413.04     5.8   27            210   6884
7       C  Naypyitaw   Normal  Female                     NaN       73.56        10  36.7800  772.3800      Ewallet  735.60     8.0   30            210   7356
8       A     Yangon   Member  Female                     NaN       36.26         2   3.6260   76.1460  Credit card   72.52     7.2   27            100   3626
9       B   Mandalay   Member  Female                     NaN       54.84         3   8.2260  172.7460  Credit card  164.52     5.9   23            185   5484
10      B   Mandalay   Member  Female                     NaN       14.48         4   2.8960   60.8160      Ewallet   57.92     4.5   25            100   1448
11      B   Mandalay   Member    Male                     NaN       25.51         4   5.1020  107.1420         Cash  102.04     6.8   22            100   2551
12      A     Yangon   Normal  Female  Electronic accessories       46.95         5  11.7375  246.4875      Ewallet  234.75     7.1   25            100   4695
13      A     Yangon   Normal    Male      Food and beverages       43.19        10  21.5950  453.4950      Ewallet  431.90     8.2   31            100   4319
14      A     Yangon   Normal  Female       Health and beauty       71.38        10  35.6900  749.4900         Cash  713.80     5.7   32            100   7138
15      B   Mandalay   Member  Female       Sports and travel       93.72         6  28.1160  590.4360         Cash  562.32     4.5   28            100   9372
16      A     Yangon   Member  Female       Health and beauty       68.93         7  24.1255  506.6355  Credit card  482.51     4.6   30            100   6893
17    NaN     Yangon   Normal    Male       Sports and travel       72.61         6  21.7830  457.4430  Credit card  435.66     6.9   24             85   7261
18    NaN     Yangon   Normal    Male      Food and beverages       54.67         3   8.2005  172.2105  Credit card  164.01     8.6   24             19   5467
19    NaN   Mandalay   Normal  Female      Home and lifestyle       40.30         2   4.0300   84.6300      Ewallet   80.60     4.4   30             85   4030
20    NaN  Naypyitaw   Member    Male  Electronic accessories       86.04         5  21.5100  451.7100      Ewallet  430.20     4.8   30             85   8604
21    NaN   Mandalay   Normal    Male       Health and beauty       87.98        55  13.1970  277.1370      Ewallet  263.94     5.1   29            100   8798
22      B   Mandalay   Normal    Male      Home and lifestyle       33.20         2   3.3200   69.7200  Credit card   66.40     4.4   28             85   3320
23      A     Yangon   Normal    Male  Electronic accessories       34.56         5   8.6400  181.4400      Ewallet  172.80     9.9   28             85   3456
24      A     Yangon   Member    Male       Sports and travel       88.63         3  13.2945  279.1845      Ewallet  265.89     6.0   29             85   8863
25      A     Yangon   Member  Female      Home and lifestyle       52.59         8  21.0360  441.7560  Credit card  420.72     8.5   25             85   5259
26      B   Mandalay   Normal    Male     Fashion accessories       33.52         1   1.6760   35.1960         Cash   33.52     6.7   27             85   3352
27      A     Yangon   Normal  Female     Fashion accessories       87.67         2   8.7670  184.1070  Credit card  175.34     7.7   29             85   8767
28      B   Mandalay   Normal  Female      Food and beverages       88.36         5  22.0900  463.8900         Cash  441.80     9.6   28             85   8836
29      A     Yangon   Normal    Male       Health and beauty       24.89         9  11.2005  235.2105         Cash  224.01     7.4   30             85   2489
30      B   Mandalay   Normal    Male     Fashion accessories       94.13         5  23.5325  494.1825  Credit card  470.65     4.8   29             19   9413
31      B   Mandalay   Member    Male       Sports and travel       78.07         9  35.1315  737.7615         Cash  702.63     4.5   22             85   7807
32      B   Mandalay   Normal    Male       Sports and travel       83.78         8  33.5120  703.7520         Cash  670.24     5.1   27             85   8378
33      A     Yangon   Normal    Male                     NaN       96.58         2   9.6580  202.8180  Credit card  193.16     5.1   26             85   9658
34      C  Naypyitaw   Member  Female                     NaN       99.42         4  19.8840  417.5640      Ewallet  397.68     7.5   22             85   9942
35      C  Naypyitaw   Member  Female                     NaN       68.12         1   3.4060   71.5260      Ewallet   68.12     6.8   26             85   6812
36    NaN     Yangon   Member    Male                     NaN       62.62         5  15.6550  328.7550      Ewallet  313.10     7.0   25             85   6262
37    NaN     Yangon   Normal  Female                     NaN       60.88        57  27.3960  575.3160      Ewallet  547.92     4.7   23             85   6088
38    NaN  Naypyitaw   Normal  Female                     NaN       54.92         8  21.9680  461.3280      Ewallet  439.36     7.6   32             85   5492
39    NaN   Mandalay   Member    Male                     NaN       30.12         8  12.0480  253.0080         Cash  240.96     7.7   27             85   3012
40    NaN   Mandalay   Member  Female                     NaN       86.72         1   4.3360   91.0560      Ewallet   86.72     7.9   22             85   8672
41    NaN  Naypyitaw   Member    Male                     NaN       56.11         2   5.6110  117.8310         Cash  112.22     6.3   27             85   5611
42    NaN   Mandalay   Member  Female                     NaN       69.12         6  20.7360  435.4560         Cash  414.72     5.6   22             85   6912
43      C  Naypyitaw   Member  Female                     NaN       98.70         8  39.4800  829.0800         Cash  789.60     7.6   27            234   9870
44      C  Naypyitaw   Member    Male                     NaN       15.37         2   1.5370   32.2770         Cash   30.74     7.2   22            234   1537
45      B   Mandalay   Member  Female  Electronic accessories       93.96         4  18.7920  394.6320         Cash  375.84     9.5   23            234   9396
46      B   Mandalay   Member    Male       Health and beauty       56.69         9  25.5105  535.7205  Credit card  510.21     8.4   27            234   5669
47      B   Mandalay   Member  Female      Food and beverages       20.01        56   9.0045  189.0945      Ewallet  180.09     4.1   22             85   2001
48      B   Mandalay   Member    Male  Electronic accessories       18.93         6   5.6790  119.2590  Credit card  113.58     8.1   22            234   1893
49      B   Mandalay   Member    Male  Electronic accessories       18.93         6   5.6790  119.2590  Credit card  113.58     8.1   22            234   1893

In [ ]:
import numpy as np 
import pandas as pd 
from sklearn.impute import KNNImputer 

imputer = KNNImputer(n_neighbors=2) 

df1 = df.select_dtypes(include=[np.number])
#fitting the imputer object 
imputer.fit(df1) 

#applying the imputer object on the dataset 
imputed_df = imputer.transform(df1) 

# print the new dataframe with imputed missing values 
print(imputed_df)

[[7.469000e+01 7.000000e+00 2.614150e+01 5.489715e+02 5.228300e+02
  9.100000e+00 2.300000e+01 2.100000e+02 7.469000e+03]
 [1.528000e+01 5.000000e+00 3.820000e+00 8.022000e+01 7.640000e+01
  9.600000e+00 2.300000e+01 2.100000e+02 1.528000e+03]
 [4.633000e+01 7.000000e+00 1.621550e+01 3.405255e+02 3.243100e+02
  7.400000e+00 2.400000e+01 2.100000e+02 4.633000e+03]
 [5.822000e+01 8.000000e+00 2.328800e+01 4.890480e+02 4.657600e+02
  8.400000e+00 2.600000e+01 2.100000e+02 5.822000e+03]
 [8.631000e+01 6.000000e+01 3.020850e+01 6.343785e+02 6.041700e+02
  5.300000e+00 3.000000e+01 2.100000e+02 8.631000e+03]
 [8.539000e+01 7.000000e+00 2.988650e+01 6.276165e+02 5.977300e+02
  4.100000e+00 3.200000e+01 2.100000e+02 8.539000e+03]
 [6.884000e+01 6.000000e+00 2.065200e+01 4.336920e+02 4.130400e+02
  5.800000e+00 2.700000e+01 2.100000e+02 6.884000e+03]
 [7.356000e+01 1.000000e+01 3.678000e+01 7.723800e+02 7.356000e+02
  8.000000e+00 3.000000e+01 2.100000e+02 7.356000e+03]
 [3.626000e+01 2.000000e+00 3.626000e+00 7.614600e+01 7.252000e+01
  7.200000e+00 2.700000e+01 1.000000e+02 3.626000e+03]
 [5.484000e+01 3.000000e+00 8.226000e+00 1.727460e+02 1.645200e+02
  5.900000e+00 2.300000e+01 1.850000e+02 5.484000e+03]
 [1.448000e+01 4.000000e+00 2.896000e+00 6.081600e+01 5.792000e+01
  4.500000e+00 2.500000e+01 1.000000e+02 1.448000e+03]
 [2.551000e+01 4.000000e+00 5.102000e+00 1.071420e+02 1.020400e+02
  6.800000e+00 2.200000e+01 1.000000e+02 2.551000e+03]
 [4.695000e+01 5.000000e+00 1.173750e+01 2.464875e+02 2.347500e+02
  7.100000e+00 2.500000e+01 1.000000e+02 4.695000e+03]
 [4.319000e+01 1.000000e+01 2.159500e+01 4.534950e+02 4.319000e+02
  8.200000e+00 3.100000e+01 1.000000e+02 4.319000e+03]
 [7.138000e+01 1.000000e+01 3.569000e+01 7.494900e+02 7.138000e+02
  5.700000e+00 3.200000e+01 1.000000e+02 7.138000e+03]
 [9.372000e+01 6.000000e+00 2.811600e+01 5.904360e+02 5.623200e+02
  4.500000e+00 2.800000e+01 1.000000e+02 9.372000e+03]
 [6.893000e+01 7.000000e+00 2.412550e+01 5.066355e+02 4.825100e+02
  4.600000e+00 3.000000e+01 1.000000e+02 6.893000e+03]
 [7.261000e+01 6.000000e+00 2.178300e+01 4.574430e+02 4.356600e+02
  6.900000e+00 2.400000e+01 8.500000e+01 7.261000e+03]
 [5.467000e+01 3.000000e+00 8.200500e+00 1.722105e+02 1.640100e+02
  8.600000e+00 2.400000e+01 1.900000e+01 5.467000e+03]
 [4.030000e+01 2.000000e+00 4.030000e+00 8.463000e+01 8.060000e+01
  4.400000e+00 3.000000e+01 8.500000e+01 4.030000e+03]
 [8.604000e+01 5.000000e+00 2.151000e+01 4.517100e+02 4.302000e+02
  4.800000e+00 3.000000e+01 8.500000e+01 8.604000e+03]
 [8.798000e+01 5.500000e+01 1.319700e+01 2.771370e+02 2.639400e+02
  5.100000e+00 2.900000e+01 1.000000e+02 8.798000e+03]
 [3.320000e+01 2.000000e+00 3.320000e+00 6.972000e+01 6.640000e+01
  4.400000e+00 2.800000e+01 8.500000e+01 3.320000e+03]
 [3.456000e+01 5.000000e+00 8.640000e+00 1.814400e+02 1.728000e+02
  9.900000e+00 2.800000e+01 8.500000e+01 3.456000e+03]
 [8.863000e+01 3.000000e+00 1.329450e+01 2.791845e+02 2.658900e+02
  6.000000e+00 2.900000e+01 8.500000e+01 8.863000e+03]
 [5.259000e+01 8.000000e+00 2.103600e+01 4.417560e+02 4.207200e+02
  8.500000e+00 2.500000e+01 8.500000e+01 5.259000e+03]
 [3.352000e+01 1.000000e+00 1.676000e+00 3.519600e+01 3.352000e+01
  6.700000e+00 2.700000e+01 8.500000e+01 3.352000e+03]
 [8.767000e+01 2.000000e+00 8.767000e+00 1.841070e+02 1.753400e+02
  7.700000e+00 2.900000e+01 8.500000e+01 8.767000e+03]
 [8.836000e+01 5.000000e+00 2.209000e+01 4.638900e+02 4.418000e+02
  9.600000e+00 2.800000e+01 8.500000e+01 8.836000e+03]
 [2.489000e+01 9.000000e+00 1.120050e+01 2.352105e+02 2.240100e+02
  7.400000e+00 3.000000e+01 8.500000e+01 2.489000e+03]
 [9.413000e+01 5.000000e+00 2.353250e+01 4.941825e+02 4.706500e+02
  4.800000e+00 2.900000e+01 1.900000e+01 9.413000e+03]
 [7.807000e+01 9.000000e+00 3.513150e+01 7.377615e+02 7.026300e+02
  4.500000e+00 2.200000e+01 8.500000e+01 7.807000e+03]
 [8.378000e+01 8.000000e+00 3.351200e+01 7.037520e+02 6.702400e+02
  5.100000e+00 2.700000e+01 8.500000e+01 8.378000e+03]
 [9.658000e+01 2.000000e+00 9.658000e+00 2.028180e+02 1.931600e+02
  5.100000e+00 2.600000e+01 8.500000e+01 9.658000e+03]
 [9.942000e+01 4.000000e+00 1.988400e+01 4.175640e+02 3.976800e+02
  7.500000e+00 2.200000e+01 8.500000e+01 9.942000e+03]
 [6.812000e+01 1.000000e+00 3.406000e+00 7.152600e+01 6.812000e+01
  6.800000e+00 2.600000e+01 8.500000e+01 6.812000e+03]
 [6.262000e+01 5.000000e+00 1.565500e+01 3.287550e+02 3.131000e+02
  7.000000e+00 2.500000e+01 8.500000e+01 6.262000e+03]
 [6.088000e+01 5.700000e+01 2.739600e+01 5.753160e+02 5.479200e+02
  4.700000e+00 2.300000e+01 8.500000e+01 6.088000e+03]
 [5.492000e+01 8.000000e+00 2.196800e+01 4.613280e+02 4.393600e+02
  7.600000e+00 3.200000e+01 8.500000e+01 5.492000e+03]
 [3.012000e+01 8.000000e+00 1.204800e+01 2.530080e+02 2.409600e+02
  7.700000e+00 2.700000e+01 8.500000e+01 3.012000e+03]
 [8.672000e+01 1.000000e+00 4.336000e+00 9.105600e+01 8.672000e+01
  7.900000e+00 2.200000e+01 8.500000e+01 8.672000e+03]
 [5.611000e+01 2.000000e+00 5.611000e+00 1.178310e+02 1.122200e+02
  6.300000e+00 2.700000e+01 8.500000e+01 5.611000e+03]
 [6.912000e+01 6.000000e+00 2.073600e+01 4.354560e+02 4.147200e+02
  5.600000e+00 2.200000e+01 8.500000e+01 6.912000e+03]
 [9.870000e+01 8.000000e+00 3.948000e+01 8.290800e+02 7.896000e+02
  7.600000e+00 2.700000e+01 2.340000e+02 9.870000e+03]
 [1.537000e+01 2.000000e+00 1.537000e+00 3.227700e+01 3.074000e+01
  7.200000e+00 2.200000e+01 2.340000e+02 1.537000e+03]
 [9.396000e+01 4.000000e+00 1.879200e+01 3.946320e+02 3.758400e+02
  9.500000e+00 2.300000e+01 2.340000e+02 9.396000e+03]
 [5.669000e+01 9.000000e+00 2.551050e+01 5.357205e+02 5.102100e+02
  8.400000e+00 2.700000e+01 2.340000e+02 5.669000e+03]
 [2.001000e+01 5.600000e+01 9.004500e+00 1.890945e+02 1.800900e+02
  4.100000e+00 2.200000e+01 8.500000e+01 2.001000e+03]
 [1.893000e+01 6.000000e+00 5.679000e+00 1.192590e+02 1.135800e+02
  8.100000e+00 2.200000e+01 2.340000e+02 1.893000e+03]
 [1.893000e+01 6.000000e+00 5.679000e+00 1.192590e+02 1.135800e+02
  8.100000e+00 2.200000e+01 2.340000e+02 1.893000e+03]]

In [ ]:
df.shape

(50, 15)

In [ ]:
import numpy as np
n = df.select_dtypes(include=[np.number])
print("The number of numerical columns: ",n.shape[1])
c = df.select_dtypes(exclude=[np.number])
print("The number of categorical columns: ",c.shape[1])

The number of numerical columns:  9
The number of categorical columns:  6

In [ ]:
z = n.sub(n.mean()).div(n.std())
#dropping the rows with outlier z-score value > 3 
df_out = n[(z > 3).all(axis=1)] 

#displaying the size of the dataframe 
print(df_out.shape)

(0, 9)

In [ ]:
n1 = n.columns
df2 = df
for i in n1:
    data = df[i] 

    #calculating min and max of the feature 
    min_data = np.min(data) 
    max_data = np.max(data) 

    #rescaling the feature using min-max normalization 
    data_normalized = (data - min_data) / (max_data - min_data) 
    df2[i] = data_normalized
    #displaying result 
print(df2.to_string())

   Branch       City Customer  Gender            Product line  Unit_price  Quantity       Tax     Total      Payment      cogs    Rating  Age  Quarterly_Tax     Price
0       A     Yangon   Member  Female       Health and beauty    0.708853  0.101695  0.648460  0.648460      Ewallet  0.648460  0.862069  0.1       0.888372  0.708853
1       C  Naypyitaw   Normal  Female  Electronic accessories    0.009418  0.067797  0.060169  0.060169         Cash  0.060169  0.948276  0.1       0.888372  0.009418
2       A     Yangon   Normal    Male      Home and lifestyle    0.374971  0.101695  0.386857  0.386857  Credit card  0.386857  0.568966  0.2       0.888372  0.374971
3       A     Yangon   Member    Male       Health and beauty    0.514952  0.118644  0.573255  0.573255      Ewallet  0.573255  0.741379  0.4       0.888372  0.514952
4       A     Yangon   Normal    Male       Sports and travel    0.845656  1.000000  0.755647  0.755647      Ewallet  0.755647  0.206897  0.8       0.888372  0.845656
5       C  Naypyitaw   Normal    Male  Electronic accessories    0.834825  0.101695  0.747160  0.747160      Ewallet  0.747160  0.000000  1.0       0.888372  0.834825
6       A     Yangon   Member  Female                     NaN    0.639981  0.084746  0.503782  0.503782      Ewallet  0.503782  0.293103  0.5       0.888372  0.639981
7       C  Naypyitaw   Normal  Female                     NaN    0.695550  0.152542  0.928841  0.928841      Ewallet  0.928841  0.672414  0.8       0.888372  0.695550
8       A     Yangon   Member  Female                     NaN    0.256416  0.016949  0.055056  0.055056  Credit card  0.055056  0.534483  0.5       0.376744  0.256416
9       B   Mandalay   Member  Female                     NaN    0.475159  0.033898  0.176291  0.176291  Credit card  0.176291  0.310345  0.1       0.772093  0.475159
10      B   Mandalay   Member  Female                     NaN    0.000000  0.050847  0.035817  0.035817      Ewallet  0.035817  0.068966  0.3       0.376744  0.000000
11      B   Mandalay   Member    Male                     NaN    0.129856  0.050847  0.093957  0.093957         Cash  0.093957  0.465517  0.0       0.376744  0.129856
12      A     Yangon   Normal  Female  Electronic accessories    0.382270  0.067797  0.268837  0.268837      Ewallet  0.268837  0.517241  0.3       0.376744  0.382270
13      A     Yangon   Normal    Male      Food and beverages    0.338003  0.152542  0.528635  0.528635      Ewallet  0.528635  0.706897  0.9       0.376744  0.338003
14      A     Yangon   Normal  Female       Health and beauty    0.669885  0.152542  0.900113  0.900113         Cash  0.900113  0.275862  1.0       0.376744  0.669885
15      B   Mandalay   Member  Female       Sports and travel    0.932894  0.084746  0.700498  0.700498         Cash  0.700498  0.068966  0.6       0.376744  0.932894
16      A     Yangon   Member  Female       Health and beauty    0.641041  0.101695  0.595327  0.595327  Credit card  0.595327  0.086207  0.8       0.376744  0.641041
17    NaN     Yangon   Normal    Male       Sports and travel    0.684365  0.084746  0.533590  0.533590  Credit card  0.533590  0.482759  0.2       0.306977  0.684365
18    NaN     Yangon   Normal    Male      Food and beverages    0.473158  0.033898  0.175619  0.175619  Credit card  0.175619  0.775862  0.2       0.000000  0.473158
19    NaN   Mandalay   Normal  Female      Home and lifestyle    0.303979  0.016949  0.065704  0.065704      Ewallet  0.065704  0.051724  0.8       0.306977  0.303979
20    NaN  Naypyitaw   Member    Male  Electronic accessories    0.842477  0.067797  0.526395  0.526395      Ewallet  0.526395  0.120690  0.8       0.306977  0.842477
21    NaN   Mandalay   Normal    Male       Health and beauty    0.865317  0.915254  0.307303  0.307303      Ewallet  0.307303  0.172414  0.7       0.376744  0.865317
22      B   Mandalay   Normal    Male      Home and lifestyle    0.220391  0.016949  0.046992  0.046992  Credit card  0.046992  0.051724  0.6       0.306977  0.220391
23      A     Yangon   Normal    Male  Electronic accessories    0.236402  0.067797  0.187202  0.187202      Ewallet  0.187202  1.000000  0.6       0.306977  0.236402
24      A     Yangon   Member    Male       Sports and travel    0.872969  0.033898  0.309873  0.309873      Ewallet  0.309873  0.327586  0.7       0.306977  0.872969
25      A     Yangon   Member  Female      Home and lifestyle    0.448670  0.118644  0.513902  0.513902  Credit card  0.513902  0.758621  0.3       0.306977  0.448670
26      B   Mandalay   Normal    Male     Fashion accessories    0.224158  0.000000  0.003663  0.003663         Cash  0.003663  0.448276  0.5       0.306977  0.224158
27      A     Yangon   Normal  Female     Fashion accessories    0.861667  0.016949  0.190549  0.190549  Credit card  0.190549  0.620690  0.7       0.306977  0.861667
28      B   Mandalay   Normal  Female      Food and beverages    0.869790  0.067797  0.541681  0.541681         Cash  0.541681  0.948276  0.6       0.306977  0.869790
29      A     Yangon   Normal    Male       Health and beauty    0.122557  0.135593  0.254685  0.254685         Cash  0.254685  0.568966  0.8       0.306977  0.122557
30      B   Mandalay   Normal    Male     Fashion accessories    0.937721  0.067797  0.579698  0.579698  Credit card  0.579698  0.120690  0.7       0.000000  0.937721
31      B   Mandalay   Member    Male       Sports and travel    0.748646  0.135593  0.885394  0.885394         Cash  0.885394  0.068966  0.0       0.306977  0.748646
32      B   Mandalay   Normal    Male       Sports and travel    0.815870  0.118644  0.842711  0.842711         Cash  0.842711  0.172414  0.5       0.306977  0.815870
33      A     Yangon   Normal    Male                     NaN    0.966565  0.016949  0.214032  0.214032  Credit card  0.214032  0.172414  0.4       0.306977  0.966565
34      C  Naypyitaw   Member  Female                     NaN    1.000000  0.050847  0.483541  0.483541      Ewallet  0.483541  0.586207  0.0       0.306977  1.000000
35      C  Naypyitaw   Member  Female                     NaN    0.631505  0.000000  0.049258  0.049258      Ewallet  0.049258  0.465517  0.4       0.306977  0.631505
36    NaN     Yangon   Member    Male                     NaN    0.566753  0.067797  0.372084  0.372084      Ewallet  0.372084  0.500000  0.3       0.306977  0.566753
37    NaN     Yangon   Normal  Female                     NaN    0.546268  0.949153  0.681522  0.681522      Ewallet  0.681522  0.103448  0.1       0.306977  0.546268
38    NaN  Naypyitaw   Normal  Female                     NaN    0.476101  0.118644  0.538466  0.538466      Ewallet  0.538466  0.603448  1.0       0.306977  0.476101
39    NaN   Mandalay   Member    Male                     NaN    0.184130  0.118644  0.277021  0.277021         Cash  0.277021  0.620690  0.5       0.306977  0.184130
40    NaN   Mandalay   Member  Female                     NaN    0.850483  0.000000  0.073769  0.073769      Ewallet  0.073769  0.655172  0.0       0.306977  0.850483
41    NaN  Naypyitaw   Member    Male                     NaN    0.490111  0.016949  0.107372  0.107372         Cash  0.107372  0.379310  0.5       0.306977  0.490111
42    NaN   Mandalay   Member  Female                     NaN    0.643278  0.084746  0.505996  0.505996         Cash  0.505996  0.258621  0.0       0.306977  0.643278
43      C  Naypyitaw   Member  Female                     NaN    0.991523  0.118644  1.000000  1.000000         Cash  1.000000  0.603448  0.5       1.000000  0.991523
44      C  Naypyitaw   Member    Male                     NaN    0.010478  0.016949  0.000000  0.000000         Cash  0.000000  0.534483  0.0       1.000000  0.010478
45      B   Mandalay   Member  Female  Electronic accessories    0.935719  0.050847  0.454761  0.454761         Cash  0.454761  0.931034  0.1       1.000000  0.935719
46      B   Mandalay   Member    Male       Health and beauty    0.496939  0.135593  0.631829  0.631829  Credit card  0.631829  0.741379  0.5       1.000000  0.496939
47      B   Mandalay   Member  Female      Food and beverages    0.065105  0.932203  0.196808  0.196808      Ewallet  0.196808  0.000000  0.0       0.306977  0.065105
48      B   Mandalay   Member    Male  Electronic accessories    0.052390  0.084746  0.109164  0.109164  Credit card  0.109164  0.689655  0.0       1.000000  0.052390
49      B   Mandalay   Member    Male  Electronic accessories    0.052390  0.084746  0.109164  0.109164  Credit card  0.109164  0.689655  0.0       1.000000  0.052390

In [ ]:
from sklearn.preprocessing import Binarizer 
import pandas as pd 
for i in n1:
    binarizer = Binarizer(threshold=25) 

    # Binarize the dataset 
    binarizer.fit_transform(df[i].values.reshape(-1,1)) 

    #Print the transformed dataset 
    print(binarizer.fit_transform(df[i].values.reshape(-1,1)))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(sparse=False) 
enc.fit(df)

#Transforming the data 
onehotlabels = enc.transform(df)
print(onehotlabels)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]

In [ ]:
def drop_duplicates(df, column):
    # Find the duplicate rows
    duplicate_rows = df[df.duplicated(column, keep=False)]

    # Find the number of unique values in the column
    num_unique_values = len(duplicate_rows[column].unique())

    # Find the number of duplicate rows
    num_duplicate_rows = len(duplicate_rows)

    # Calculate the percentage of rows that are duplicates
    pct_duplicate_rows = num_duplicate_rows / (num_duplicate_rows + num_unique_values)

    # If more than 50% of the rows are duplicates, drop the duplicate rows
    if pct_duplicate_rows > 0.5:
        return df.drop_duplicates(subset=column)
    else:
        return df

In [ ]:
df = pd.get_dummies (columns=['Branch'])
print df

TypeError: ignored